comment:
    layout: "diff"
    behavior: default # update, if exists. Otherwise post new
    require_changes: yes # only post the comment if coverage changes

coverage:
    status:
        project: false
        changes: false
        patch:
            default:
                enabled: true
                target: 80%
                threshold: 50%
