#!/bin/sh
set -xe

# Install dependencies
apt-get update
apt-get install -y \
    "$DC=$DMD-$(lsb_release -cs)" \
    libglib2.0-dev \
    libpcre3-dev \
    libxml2-dev \
    libxslt-dev \
    libebtree6-dev \
    liblzo2-dev \
    libreadline-dev \
    libbz2-dev \
    zlib1g-dev \
    libssl-dev \
    libgcrypt11-dev \
    libgpg-error-dev
