#!/bin/sh
# Copyright sociomantic labs GmbH 2017.
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.txt or copy at
# http://www.boost.org/LICENSE_1_0.txt)
set -xeu

# Test basic usage with no DIST
beaver install
cat beaver.Dockerfile.generated
rm beaver.Dockerfile.generated
beaver docker run test -f /BUILT-1-Dockerfile -a -f /BUILT-2-build
test "$(beaver docker run lsb_release -cs)" = "$(lsb_release -cs)"

# Test basic usage with DIST
DIST=xenial beaver install
cat beaver.Dockerfile.generated
beaver docker run test -f /BUILT-1-Dockerfile -a -f /BUILT-2-build
test "$(beaver docker run lsb_release -cs)" = xenial
